### PR TITLE
Respect http(s) proxy environment variables

### PR DESCRIPTION
**Pull request by wcho**
This will resolve issue#4
https://github.com/sourcemint/util-js/issues/4

### CODE REVIEW

**Comment by cadorn** [comment]
Thanks! Should be able to merge this soon.

**Comment by cadorn** [comment]
This will be in the next `sm` release (0.3). See 0a93bad34d47fd4e57f3186c842c91a2fdf545f0

**Comment by mattgoldspink** [comment]
The above fixes don't quite work - see my comment here for details:

https://github.com/sourcemint/util-js/commit/0a93bad34d47fd4e57f3186c842c91a2fdf545f0#commitcomment-2138186

**Comment by cadorn** [comment]
Thanks! Fixed. Please test.

**Pull request closed without merging**
